### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Ostrich5yw** [lflfdxfn/DPLAN-Implementation#3]
Could you share your datasets？I tried to use my own formatted dataset，but it can't work

**Comment by lflfdxfn** [comment]
> Could you share your datasets？I tried to use my own formatted dataset，but it can't work

I can't find the older version dataset for this code either, cause I have integrated this model in my own work and the data structure is totally different. 

For your own dataset, you can find codes to read the training data and the testing data in the main.py file.
For example, for the NB15 dataset, there would be several training datasets and one testing dataset
1. train data: 75 table=pd.read_csv(undata_path). The for loop outside this code is trying to go through all training datasets that consider the different known anomalous classes.
2. test data: 64 test_dataset=test_table.values.
