### ISSUE TITLE
Dataset Preprocessing

### ISSUE THREAD

**Issue by elisejiuqizhang** [lflfdxfn/DPLAN-Implementation#4]
Hey Zhi,

Would it be possible for you to share how you processed the NB15 datasets? I might have a few questions about data preprocessing, 

e.g., how do we deal with the following categorical features, 'proto', 'service', 'state', that are not numerical? 

Also, regarding line 89 in the 'main.py' file which is `weights_file=os.path.join(model_path,"{}_{}_{}_weights.h4f".format(subset,i,data_name))` - I was wondering where this weight file should initially come from.

Best,
Elise

**Comment by ThisisHubert** [comment]
Since this is an unofficial repo, I think this is not reproducable. It didn't work on my end either

**Comment by lflfdxfn** [comment]
> 
Hey Elise,

Sorry for replying so late. I am busy these days and pay little attention to the Github account. 

1. For categorical features, generally, we will convert them into one-hot encoded vectors for further calculation. Here I use the function get_dummies in pandas package.
2. The weights_file here is named for the file we want to store the information of our model in the latter part. Weights in the model will be stored in this file after the training process and reused in the testing process.

Best, 
Zhi

**Comment by lflfdxfn** [comment]
> Hey Zhi,
> 
> Would it be possible for you to share how you processed the NB15 datasets? I might have a few questions about data preprocessing,
> 
> e.g., how do we deal with the following categorical features, 'proto', 'service', 'state', that are not numerical?
> 
> Also, regarding line 89 in the 'main.py' file which is `weights_file=os.path.join(model_path,"{}_{}_{}_weights.h4f".format(subset,i,data_name))` - I was wondering where this weight file should initially come from.
> 
> Best, Elise

Hey Elise,

Sorry for replying so late. I am busy these days and pay little attention to the Github account.

For categorical features, generally, we will convert them into one-hot encoded vectors for further calculation. Here I use the function get_dummies in pandas package.
The weights_file here is named for the file we want to store the information of our model in the latter part. Weights in the model will be stored in this file after the training process and reused in the testing process.
Best,
Zhi
